trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: "3.11"
  imageRepository: "bankcore-api"

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: "$(pythonVersion)"

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements-dev.txt
  displayName: Install dependencies

- script: |
    black --check .
    isort --check-only .
    flake8 .
  displayName: Code quality

- script: |
    pytest -v --cov=src --cov=api
  displayName: Run tests

- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: api/Dockerfile
    containerRegistry: bankcore-acr
    tags: |
      $(Build.BuildId)
      latest